name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get sources
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          # renovate: dataSource=nodejs
          node-version: v20.8.1

      - name: Check Node.js version
        run: node -v
